### ISSUE TITLE
TODO: Patches-- verify & confirm that changes are Stack-safe (don't cause stack overflows)

### ISSUE THREAD

**Issue by TAbdiukov** [TAbdiukov/Ikejime#9]
- [x] [p-AlcatelContentManager_uncripple.py](https://github.com/TAbdiukov/Ikejime/blob/main/p-AlcatelContentManager_uncripple.py) - **NOPs out bad jump - safe on stack**
- [x] [p-AltServer_preWin10support.py](https://github.com/TAbdiukov/Ikejime/blob/main/p-AltServer_preWin10support.py) - **very basic string patch - stack-safe**

- [x] [p-CarmageddonTDR2000_killTimer.py](https://github.com/TAbdiukov/Ikejime/blob/main/p-CarmageddonTDR2000_killTimer.py) - **safe on CPU stack, but theoretically UNSAFE on FPU register stack.** The game appears to use FPU in JIT manner, nonetheless: v2 patch is made.
    * View in WinHEX (v1):  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/36c7ac6f-4ae6-4607-861d-42b9307a0a14)  
    * View in Immunity Debugger (v1):  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/d9b7ff65-940f-4826-93f8-214af4dedcfe)
    * View in IDA Pro, before patch (v1):  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/32084568-443c-4529-8b66-bb3fcdb3af57)
    * View in IDA Pro, after patch (v1):  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/daf245b2-6cc2-4a62-aedf-66d8008a3b43)

- [x] [p-CarmageddonTDR2000_reverseTimer.py](https://github.com/TAbdiukov/Ikejime/blob/main/p-CarmageddonTDR2000_reverseTimer.py) - FPU (x87): 0x64 [float sub] -> 0x44 [float add] for reverse function - **Both CPU and FPU stack-safe**
- [x] [p-K10stat_anyCPUpatch.py](https://github.com/TAbdiukov/Ikejime/blob/main/p-K10stat_anyCPUpatch.py) - Replacing conditional jumps to [UNconditional](https://youtu.be/ixhWUXZJsDw?t=38) and NOPing some other jumps - **Safe on stack**
- [x] [p-Swype.exe_unLim+noDX10.py](https://github.com/TAbdiukov/Ikejime/blob/main/p-Swype.exe_unLim%2BnoDX10.py) MAIN - patches (NOPs) out `CMP, JNZ, CMP JNZ` cluster - **safe on stack, and (following the next CMP instruction), safe on registry flags!**
    * View in WinHex:  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/39e08aec-509f-446d-b83a-3180a6662945)
    * View in IDA (would be similar in Immunity Debugger/x64dbg):  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/dbc53462-0f2c-4b72-af8b-b9465c478b4c)
    
- [x] [FLAG_UNSAFE] [p-Swype.exe_unLim+noDX10.py](https://github.com/TAbdiukov/Ikejime/blob/main/p-Swype.exe_unLim%2BnoDX10.py) DX10 v1 - Right in the function beginning, `push ecx; push esi` are replaced by `ret 4`. INSIDE function, patch is stack safe. HOWEVER, in function calls, there is `push ebx`, making **the patch stack-UNSAFE** (slow stack corruption)
    * View in WinHex:  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/7bae9e20-64aa-45d6-9ce4-9ba0abb0dd84)
    * View of patched (to `ret 4` part) in IDA Pro:  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/01971019-f2c6-4de3-9e30-4aac32d38a83)
    * View of XREF FROM functions in IDA Pro:  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/3322007f-c5c1-4bd4-90c4-2608ea0b61b6)

- [x] [p-Swype.exe_unLim+noDX10.py](https://github.com/TAbdiukov/Ikejime/blob/main/p-Swype.exe_unLim%2BnoDX10.py) DX10 v2 - **conditional jump is made UNconditional - stack-safe**
    * View in WinHex:  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/58f3413b-9b12-409d-b0ef-4d2cda174fac)
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/9cdff96a-3a3d-4105-888f-82831d1daf39)
    * View in IDA Pro (before patching):   
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/492c6930-fb38-4809-b7e7-41074a8bb53b)
    * View in IDA Pro (after patching):  
    ![image](https://github.com/TAbdiukov/Ikejime/assets/18607514/bac7ad23-7d7d-4512-a37c-9a2e5e23374f)

**Comment by TAbdiukov** [comment]
TODO:

**Comment by TAbdiukov** [comment]
All required changes are made
